name: Build & Publish product service Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'product-service/**'

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./product-service/
          push: true
          tags: thakiyudheen/ecommerce-product-service:latest
